import java.util.Scanner;
import java.util.Random;

//Welcome my name is Farhan Ashraf and this is my first task Number Guessing GAME

public class GuessNumber {
    public static void main(String[] args) {

        /*
         Creating a game "Number Guessing Game" which allow the user to guess number generated by the system.
         The Following steps are involve:
         1.The system generates a random number from a given range 1 to 100.
         2.The user is prompted to enter their given number in a displayed dialogue box.
         3.The computer then tells if the entered number matches the guesses number, or it is higher/lower than
           the generated number.
         4.The game continues under the user guessing the number.
         5.Some details are add:
          -Limiting the number of attempts
          -Giving points on the number of attempts
          -Displaying score
        */

        Scanner sc = new Scanner(System.in);
        Random rand = new Random();

        //setting the target number
        int lowerBound = 1;
        int upperBound = 100;
        int targetNumber = rand.nextInt(upperBound - lowerBound + 1) + lowerBound;

        //setting number of guess by user and maximum guess allowed
        int numberOfGuess = 0;
        int maxGuess = 8;

        // total points
        float points = 100.00F;

        //start of game
        System.out.println("----------Welcome to----------");
        System.out.println("THE NUMBER GUESSING GAME!\n");
        System.out.println("A number between " + lowerBound + " and " + upperBound + " is selected.");
        System.out.println("You have " + maxGuess + " guess to find the number.");

        //to check for number of guess by the user
        while (numberOfGuess < maxGuess)
        {
            System.out.print("\nGuessed #" + (numberOfGuess + 1) + "\nEnter the number: ");
            int guess = sc.nextInt();
            numberOfGuess++;

            //checking if the number guessed by the user is more or less than 1 - 100
            if (guess < lowerBound || guess > upperBound)
            {
                System.out.println("Please enter a number between " + lowerBound + " and " + upperBound + ".");
                continue;
            }

            //if the guessed number is equal to the target number
            if (guess == targetNumber)
            {
                System.out.println("\nCongratulations! You've guessed the correct number: " + targetNumber);
                System.out.println("Total points you earned " + points); //displays points after correct guess
                break;
            }

            //if guessed number is smaller than target number
            else if (guess < targetNumber)
            {
                System.out.println("\nNumber is too low.");
            }

            //if guessed number is larger than target number
            else
            {
                System.out.println("\nNumber is to high.");
            }
            //12.5 points deducted after every wrong guess
            points -= 12.5F;
        }

        //after 8 attempts game gets over
        if (numberOfGuess >= maxGuess)
        {
            System.out.println("\nGame over!");
            System.out.println("The correct number was: " + targetNumber);
        }

        sc.close();
    }
}
// Thank You